name       : bolt
version    : 0.9.2
release    : 7
source     :
    - https://gitlab.freedesktop.org/bolt/bolt/-/archive/0.9.2/bolt-0.9.2.tar.bz2 : 42c2a1f8cdf5bf7b7536c4c8278eff2aee985c6bb082a89be0ee248239c48d75
license    : 
    - LGPL-2.1-or-later # Source code
    - GPL-2.0-or-later # Udev rules file
component  : system.utils
summary    : Thunderbolt device manager
description: |
    Userspace system daemon to enable security levels for Thunderbolt 3 on GNU/Linux.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - pkgconfig(umockdev-1.0)
    - asciidoc
setup      : |
    %patch -p1 < $pkgfiles/0001-test-exported-is-not-allowed-in-our-sandbox.patch

    %meson_configure -Dprivileged-group=sudo
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
