name       : bolt
version    : 0.9.1
release    : 6
source     :
    - https://gitlab.freedesktop.org/bolt/bolt/-/archive/0.9.1/bolt-0.9.1.tar.bz2 : dcdcff59feff902940d337307ee51e296423f9ea2ac4649f8c7f62d789748118
license    : LGPL-2.1-or-later
component  : system.utils
summary    : Thunderbolt device manager
description: |
    Userspace system daemon to enable security levels for Thunderbolt 3 on GNU/Linux.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - pkgconfig(umockdev-1.0)
    - asciidoc
setup      : |
    %patch -p1 < $pkgfiles/0001-test-exported-is-not-allowed-in-our-sandbox.patch

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
