name       : bolt
version    : '0.7'
release    : 4
source     :
    - https://gitlab.freedesktop.org/bolt/bolt/-/archive/0.7/bolt-0.7.tar.bz2 : e0b626392cb58e84f8a79803dc3a8b49e831bdb8145f01be9c6b23156444a3b6
license    : LGPL-2.1-or-later
component  : system.utils
summary    : Thunderbolt device manager
description: |
    Userspace system daemon to enable security levels for Thunderbolt 3 on GNU/Linux.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - pkgconfig(umockdev-1.0)
    - asciidoc
setup      : |
    %patch -p1 < $pkgfiles/0001-test-exported-is-not-allowed-in-our-sandbox.patch

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
